package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class AddEnrollmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEnrollmentForm.class.getName());

    Connection conn=null;
    PreparedStatement pst=null;
    
    public AddEnrollmentForm() {
        initComponents();
        setExtendedState(AddEnrollmentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studenid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        coursecode = new javax.swing.JLabel();
        coursename = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        CourseCode = new javax.swing.JTextField();
        CourseName = new javax.swing.JTextField();
        Credits = new javax.swing.JTextField();
        AddEnrollmentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        studenid.setText("Student ID:");
        getContentPane().add(studenid);
        studenid.setBounds(20, 80, 70, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Enrollment");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 190, 40);

        coursecode.setText("Course Code:");
        getContentPane().add(coursecode);
        coursecode.setBounds(20, 100, 100, 40);

        coursename.setText("Course Name:");
        getContentPane().add(coursename);
        coursename.setBounds(20, 140, 100, 20);

        credits.setText("Credits:");
        getContentPane().add(credits);
        credits.setBounds(20, 150, 50, 60);

        StudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDActionPerformed(evt);
            }
        });
        getContentPane().add(StudentID);
        StudentID.setBounds(180, 80, 190, 22);
        getContentPane().add(CourseCode);
        CourseCode.setBounds(180, 110, 190, 22);
        getContentPane().add(CourseName);
        CourseName.setBounds(180, 140, 190, 22);
        getContentPane().add(Credits);
        Credits.setBounds(180, 170, 190, 22);

        AddEnrollmentButton.setText("Add");
        AddEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddEnrollmentButton);
        AddEnrollmentButton.setBounds(80, 240, 80, 40);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(240, 240, 80, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 420, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentManagement().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEnrollmentButtonActionPerformed
        // TODO add your handling code here:
        if (StudentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student ID cannot be empty!");
            return;
        }
        if (CourseCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course Code cannot be empty!");
            return;
        }
        if (CourseName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course Name cannot be empty!");
            return;
        }
        if (Credits.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Credits cannot be empty!");
            return;
        }
        
        String sql="insert into Group2_Enrollments(StudentID, CourseCode, CourseName, Credits) values(?, ?, ?, ?)";
        try{
            conn=OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql);
            pst.setString(1, StudentID.getText());
            pst.setString(2, CourseCode.getText());
            pst.setString(3, CourseName.getText());
            pst.setString(4, Credits.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Enrollment Added");
            StudentID.setText("");
            CourseCode.setText("");
            CourseName.setText("");
            Credits.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
        }
    }//GEN-LAST:event_AddEnrollmentButtonActionPerformed

    private void StudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddEnrollmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEnrollmentButton;
    private javax.swing.JTextField CourseCode;
    private javax.swing.JTextField CourseName;
    private javax.swing.JTextField Credits;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField StudentID;
    private javax.swing.JLabel coursecode;
    private javax.swing.JLabel coursename;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel studenid;
    // End of variables declaration//GEN-END:variables
}
