package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class AddStudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddStudentForm.class.getName());

    Connection conn=null;
    PreparedStatement pst=null;
    
    public AddStudentForm() {
        initComponents();
        setExtendedState(AddStudentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Surname = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        Email = new javax.swing.JTextField();
        Department = new javax.swing.JComboBox<>();
        Year = new javax.swing.JSpinner();
        GPA = new javax.swing.JTextField();
        AddStudentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 192, 35);

        jLabel2.setText("StudentID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 53, 70, 16);

        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 40);

        jLabel4.setText("Surname :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 70, 20);

        jLabel5.setText("Gender :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 70, 20);

        jLabel6.setText("Email :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 166, 70, 30);

        jLabel7.setText("Department :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 200, 100, 40);

        jLabel8.setText("Year :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 250, 40, 20);

        jLabel9.setText("GPA :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 40, 30);
        getContentPane().add(StudentID);
        StudentID.setBounds(110, 50, 200, 22);
        getContentPane().add(Name);
        Name.setBounds(110, 80, 200, 22);
        getContentPane().add(Surname);
        Surname.setBounds(110, 110, 200, 22);

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        getContentPane().add(Gender);
        Gender.setBounds(110, 140, 200, 22);
        getContentPane().add(Email);
        Email.setBounds(110, 170, 200, 22);

        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Computer Engineering", "Electrical Engineering", "Electronics Engineering", "Mechanical Engineering", "Civil Engineering", "Industrial Engineering", "Artificial Intelligence", "Data Science", "Information Systems", "Business Administration", "Economics", "International Relations", "Psychology", "Mathematics", "Physics", "Chemistry", "Biology", "Medicine", "Law", "Architecture" }));
        getContentPane().add(Department);
        Department.setBounds(110, 210, 200, 22);
        getContentPane().add(Year);
        Year.setBounds(110, 250, 70, 22);
        getContentPane().add(GPA);
        GPA.setBounds(110, 280, 64, 22);

        AddStudentButton.setText("Add Student");
        AddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudentButton);
        AddStudentButton.setBounds(100, 360, 130, 50);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(280, 360, 130, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-7, -4, 530, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        // TODO add your handling code here:
        if (StudentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student ID cannot be empty!");
            return;
        }
        if (Name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty!");
            return;
        }
        if (Surname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Surname cannot be empty!");
            return;
        }
        if (Email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email cannot be empty!");
            return;
        }
        if (GPA.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "GPA cannot be empty!");
            return;
        }
    
        String sql="insert into Group2_Students values(?, ?, ?, ?, ?, ?, ?, ?);";
        try{
            conn=OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql);
            pst.setString(1, StudentID.getText());
            pst.setString(2, Name.getText());
            pst.setString(3, Surname.getText());
            pst.setString(4, Gender.getSelectedItem().toString());
            pst.setString(5, Email.getText());
            pst.setString(6, Department.getSelectedItem().toString());
            pst.setString(7, Year.getValue().toString());
            pst.setString(8, GPA.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Student Added");
            StudentID.setText("");
            Name.setText("");
            Surname.setText("");
            Email.setText("");
            GPA.setText("");
            Gender.setSelectedIndex(0);
            Department.setSelectedIndex(0);
            Year.setValue(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddStudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JTextField Email;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField GPA;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextField Surname;
    private javax.swing.JSpinner Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
