package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class DeleteEnrollmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteEnrollmentForm.class.getName());
    Connection conn=null;
    Statement st= null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    /**
     * Creates new form DeleteEnrollmentForm
     */
    public DeleteEnrollmentForm() {
        initComponents();
        setExtendedState(DeleteEnrollmentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DeleteEnrollmentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        EnrollmentID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        SearchDeleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Delete Enrollment");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, -20, 210, 90);

        DeleteEnrollmentButton.setText("Delete");
        DeleteEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteEnrollmentButton);
        DeleteEnrollmentButton.setBounds(80, 240, 80, 40);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(220, 240, 80, 40);

        jLabel6.setText("Enter Enrollment ID:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 50, 130, 40);

        EnrollmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentIDActionPerformed(evt);
            }
        });
        getContentPane().add(EnrollmentID);
        EnrollmentID.setBounds(140, 60, 200, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 300, 110);

        jLabel2.setText("Enrollment Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 100, 140, 16);

        SearchDeleteButton.setText("Search");
        SearchDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchDeleteButton);
        SearchDeleteButton.setBounds(352, 60, 80, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-3, -4, 460, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDeleteButtonActionPerformed
                                                                                        
    String sql = "SELECT * FROM Group2_Enrollments WHERE EnrollmentID = ?";
    
    try {
        conn=OnlineDB.connectOnlineDB();
        pst = conn.prepareStatement(sql);
        pst.setString(1, EnrollmentID.getText());
        rs = pst.executeQuery();

        if (rs.next()) {
           
            String sId = rs.getString("StudentID");
            String courseName = rs.getString("CourseName");
            String courseCode = rs.getString("CourseCode");
            String credits = rs.getString("Credits");

           
            jTextArea1.setText("Student ID: " + sId + "\n" +
                               "Course Code: " + courseCode + "\n" +
                               "Course Name: " + courseName + "\n" +
                               "Credits: " + credits);
        } else {
            jTextArea1.setText("No enrollment found with ID: " + EnrollmentID.getText());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
    }


    }//GEN-LAST:event_SearchDeleteButtonActionPerformed

    private void DeleteEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEnrollmentButtonActionPerformed
        if (EnrollmentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an Enrollment ID first!");
            return;
        }
        
        String sql = "DELETE FROM Group2_Enrollments WHERE EnrollmentID = ?";
    
        try {
            conn=OnlineDB.connectOnlineDB();
            pst = conn.prepareStatement(sql);
            pst.setString(1, EnrollmentID.getText());
            int result = pst.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Enrollment deleted successfully!");

                EnrollmentID.setText("");
                jTextArea1.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Record could not be found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete Error: " + e.getMessage());
        }

    }//GEN-LAST:event_DeleteEnrollmentButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentManagement().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void EnrollmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnrollmentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteEnrollmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteEnrollmentButton;
    private javax.swing.JTextField EnrollmentID;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
