package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class EnrollmentManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollmentManagement.class.getName());
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 
    
    public EnrollmentManagement() {
        initComponents();
        setExtendedState(EnrollmentManagement.MAXIMIZED_BOTH);
        conn = OnlineDB.connectOnlineDB(); 
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DeleteEnrollmentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        UpdateEnrollmentButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ShowListEnrollmentButton = new javax.swing.JButton();
        AddEnrollmentButton1 = new javax.swing.JButton();
        SearchEnrollmentButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Enrollment Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 300, 32);

        DeleteEnrollmentButton.setText("Delete Enrollment");
        DeleteEnrollmentButton.setAutoscrolls(true);
        DeleteEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DeleteEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteEnrollmentButton);
        DeleteEnrollmentButton.setBounds(170, 110, 130, 50);

        ExitButton.setForeground(new java.awt.Color(204, 0, 0));
        ExitButton.setText("Exit");
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(400, 280, 60, 30);

        UpdateEnrollmentButton.setText("Update Enrollment");
        UpdateEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpdateEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateEnrollmentButton);
        UpdateEnrollmentButton.setBounds(250, 200, 140, 50);

        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(10, 20, 60, 20);

        ShowListEnrollmentButton.setText("Show Enrollment List");
        ShowListEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ShowListEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowListEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowListEnrollmentButton);
        ShowListEnrollmentButton.setBounds(320, 110, 140, 50);

        AddEnrollmentButton1.setText("Add Enrollment");
        AddEnrollmentButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AddEnrollmentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEnrollmentButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(AddEnrollmentButton1);
        AddEnrollmentButton1.setBounds(40, 110, 120, 50);

        SearchEnrollmentButton.setText("Search Enrollment");
        SearchEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SearchEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchEnrollmentButton);
        SearchEnrollmentButton.setBounds(90, 200, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void DeleteEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEnrollmentButtonActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable(){ 
           public void run() {
               new DeleteEnrollmentForm().setVisible(true);
           }
       });
       this.dispose();
    }//GEN-LAST:event_DeleteEnrollmentButtonActionPerformed

    private void UpdateEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEnrollmentButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEnrollmentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_UpdateEnrollmentButtonActionPerformed

    private void AddEnrollmentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEnrollmentButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEnrollmentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_AddEnrollmentButton1ActionPerformed

    private void SearchEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEnrollmentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
               new SearchEnrollmentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_SearchEnrollmentButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new MainMenuForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ShowListEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowListEnrollmentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable(){ 
            public void run(){
                new ShowListEnrollmentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ShowListEnrollmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnrollmentManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEnrollmentButton1;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteEnrollmentButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchEnrollmentButton;
    private javax.swing.JButton ShowListEnrollmentButton;
    private javax.swing.JButton UpdateEnrollmentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
