package studentManagementSystem;

import javax.swing.JOptionPane;
 
public class MainMenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuForm.class.getName());
    private String loggedUsername;
    /**
     * Creates new form MainForm
     */
    public MainMenuForm() {
        initComponents();
        setExtendedState(MainMenuForm.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public MainMenuForm(String username) {
        initComponents();
        setExtendedState(MainMenuForm.MAXIMIZED_BOTH);
        this.loggedUsername = username;
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitButton = new javax.swing.JLabel();
        StudentManagementButton = new javax.swing.JButton();
        EnrollmentManagementButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ExitButtonMain = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        ExitButton.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        StudentManagementButton.setText("Student Management");
        StudentManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StudentManagementButton);
        StudentManagementButton.setBounds(90, 120, 210, 80);

        EnrollmentManagementButton.setText("Enrollment Management");
        EnrollmentManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentManagementButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EnrollmentManagementButton);
        EnrollmentManagementButton.setBounds(350, 120, 210, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Main Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 50, 140, 50);

        ExitButtonMain.setForeground(new java.awt.Color(204, 0, 0));
        ExitButtonMain.setText("Exit");
        ExitButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonMainActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButtonMain);
        ExitButtonMain.setBounds(290, 290, 75, 23);

        Settings.setText("Profile Settings");
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        getContentPane().add(Settings);
        Settings.setBounds(260, 230, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentManagementButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
            }
        });
        this.dispose();

    }//GEN-LAST:event_StudentManagementButtonActionPerformed

    private void EnrollmentManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentManagementButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentManagement().setVisible(true);
            }
        });
        this.dispose();

    }//GEN-LAST:event_EnrollmentManagementButtonActionPerformed

    private void ExitButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonMainActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMainActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileSettingsForm(loggedUsername).setVisible(true);
            }
        }); 
        this.dispose(); 
    }//GEN-LAST:event_SettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnrollmentManagementButton;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JButton ExitButtonMain;
    private javax.swing.JButton Settings;
    private javax.swing.JButton StudentManagementButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
