package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
    
public class ProfileSettingsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileSettingsForm.class.getName());
    Connection conn = null;
    PreparedStatement pst = null;
    /**
     * Creates new form ProfileSettingsForm
     */
    public ProfileSettingsForm() {
        initComponents();
        setExtendedState(ProfileSettingsForm.MAXIMIZED_BOTH);
        conn = OnlineDB.connectOnlineDB();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public ProfileSettingsForm(String loggedUsername) {
        initComponents();
        setExtendedState(ProfileSettingsForm.MAXIMIZED_BOTH);
        conn = OnlineDB.connectOnlineDB();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        Username.setText(loggedUsername);
        Username.setEditable(false);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        NewPassword = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Profile Settings");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 190, 60);

        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 70, 40);

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username);
        Username.setBounds(120, 70, 150, 22);

        jLabel3.setText("Current Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 100, 20);

        jLabel4.setText("New Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 90, 20);

        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 200, 110, 20);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(160, 140, 100, 22);
        getContentPane().add(NewPassword);
        NewPassword.setBounds(160, 170, 100, 22);
        getContentPane().add(ConfirmPassword);
        ConfirmPassword.setBounds(160, 200, 100, 22);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton);
        SaveButton.setBounds(170, 250, 72, 23);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(280, 250, 75, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -4, 410, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:                                           
        String username = Username.getText(); 
        String currentPassword = Password.getText();
        String newPassword = NewPassword.getText();
        String confirmPassword = ConfirmPassword.getText();

        if (currentPassword.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Current Password cannot be empty!");
            return;
        }
        if (newPassword.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "New Password cannot be empty!");
            return;
        }
        if (confirmPassword.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirm Password cannot be empty!");
            return;
        }
        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "New passwords do not match!");
            return;
        }

        try {
            String sql = "UPDATE Group2_Login SET Password=? WHERE Username=? AND Password=?";
            conn = OnlineDB.connectOnlineDB();
            pst = conn.prepareStatement(sql);
            pst.setString(1, newPassword);
            pst.setString(2, username);
            pst.setString(3, currentPassword);

            int result = pst.executeUpdate();

            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Password updated successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Current Password incorrect!");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfileSettingsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
