package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class SearchEnrollmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchEnrollmentForm.class.getName());
    Connection conn=null;
    Statement st= null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    /**
     * Creates new form SearchEnrollmentForm
     */
    public SearchEnrollmentForm() {
        initComponents();
        setExtendedState(SearchEnrollmentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnrollmentID = new javax.swing.JTextField();
        SearchEnrollmentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ExitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Search Enrollment");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 261, 32);

        jLabel3.setText("Enter Enrollment ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 120, 20);
        getContentPane().add(EnrollmentID);
        EnrollmentID.setBounds(130, 60, 200, 22);

        SearchEnrollmentButton.setText("Search ");
        SearchEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchEnrollmentButton);
        SearchEnrollmentButton.setBounds(350, 60, 90, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 330, 140);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(380, 300, 72, 23);

        jLabel4.setText("Enrollment Information");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 120, 140, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -4, 490, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEnrollmentButtonActionPerformed
                               
        String sql = "SELECT * FROM Group2_Enrollments WHERE EnrollmentID = ?";

        try {
            conn=OnlineDB.connectOnlineDB();
            pst = conn.prepareStatement(sql);

            String searchID = EnrollmentID.getText().trim();

            if (searchID.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter an Enrollment ID!");
                return;
            }

            pst.setString(1, searchID);
            rs = pst.executeQuery();


            if (rs.next()) {
                String sId = rs.getString("StudentID");
                String cCode = rs.getString("CourseCode");
                String cName = rs.getString("CourseName");
                String credits = rs.getString("Credits");

                jTextArea1.setText(

                    "Enrollment ID : " + searchID + "\n" +
                    "Student ID    : " + sId + "\n" +
                    "Course Code   : " + cCode + "\n" +
                    "Course Name   : " + cName + "\n" +
                    "Credits       : " + credits
                );
            } else {
                jTextArea1.setText("");
                JOptionPane.showMessageDialog(null, "No record found with ID: " + searchID);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        } finally {
            try { if(rs != null) rs.close(); if(pst != null) pst.close(); } catch(Exception e) {}
        }
    }//GEN-LAST:event_SearchEnrollmentButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentManagement().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchEnrollmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnrollmentID;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchEnrollmentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
