package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class SearchStudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchStudentForm.class.getName());
    Connection conn=null;
    Statement st = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form SearchForm
     */
    public SearchStudentForm() {
        initComponents();
        setExtendedState(SearchStudentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Search Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(197, 6, 184, 32);

        jLabel2.setText("Enter Student ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 110, 20);
        getContentPane().add(StudentID);
        StudentID.setBounds(170, 60, 230, 22);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton);
        SearchButton.setBounds(440, 60, 80, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 480, 150);

        jLabel3.setText("Student Information");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 120, 16);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(260, 300, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-3, -4, 600, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
                                     
        String sql = "SELECT * FROM Group2_Students WHERE StudentID = ?";

        try {
            conn=OnlineDB.connectOnlineDB();
            pst = conn.prepareStatement(sql);
            pst.setString(1, StudentID.getText());
            rs = pst.executeQuery();

            if (rs.next()) {

                String name = rs.getString("Name");
                String surname = rs.getString("Surname");
                String gender = rs.getString("Gender");
                String email = rs.getString("Email");
                String department = rs.getString("Department");
                String year = rs.getString("Year");
                String gpa = rs.getString("Gpa"); 


                jTextArea1.setText("Full Name: " + name + " " + surname + "\n" +
                                   "Gender: " + gender + "\n" +
                                   "E-mail: " + email + "\n" +
                                   "Department: " + department + "\n" +
                                   "Year: " + year + "\n" +
                                   "GPA: " + gpa);
            } else {
                jTextArea1.setText("No student found with ID: " + StudentID.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchStudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField StudentID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
