package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ShowListStudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowListStudentForm.class.getName());
    Connection conn=null;
    Statement st= null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    /**
     * Creates new form ShowListStudentForm
     */
    public ShowListStudentForm() {
        initComponents();
        setExtendedState(ShowListStudentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        ShowListStudent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Name", "Surname", "Gender", "Email", "Department", "Year", "GPA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        studentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Name", "Surname", "Gender", "Email", "Department", "Year", "GPA"
            }
        ));
        jScrollPane2.setViewportView(studentList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 800, 220);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student List");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 40, 220, 32);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(440, 360, 90, 40);

        ShowListStudent.setText("Show List");
        ShowListStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowListStudentActionPerformed(evt);
            }
        });
        getContentPane().add(ShowListStudent);
        ShowListStudent.setBounds(280, 360, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 840, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ShowListStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowListStudentActionPerformed
        String sql  = "select * from Group2_Students;";     
        try
        {
            conn=OnlineDB.connectOnlineDB();
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel) studentList.getModel();
            while(rs.next())
            {
                String id = rs.getString("StudentID");
                String name = rs.getString("Name");
                String surname = rs.getString("Surname");
                String gender = rs.getString("Gender");
                String email = rs.getString("Email");
                String department = rs.getString("Department");
                String year = rs.getString("Year");
                String gpa = rs.getString("Gpa");
                tm.addRow(new Object[]{id, name, surname, gender, email, department, year, gpa});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_ShowListStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShowListStudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ShowListStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable studentList;
    // End of variables declaration//GEN-END:variables
}
