package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class StudentManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentManagementForm.class.getName());

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 
    
   
    /**
     * Creates new form StudentManagementForm
     */
    public StudentManagementForm() {
        initComponents();
        setExtendedState(StudentManagementForm.MAXIMIZED_BOTH);
        conn = OnlineDB.connectOnlineDB(); 
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AddStudentButton = new javax.swing.JButton();
        UpdateStudentButton = new javax.swing.JButton();
        DeleteStudentButton = new javax.swing.JButton();
        SearchStudentButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ShowListStudentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Student Management");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 50, 250, 34);

        AddStudentButton.setText("Add Student");
        AddStudentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudentButton);
        AddStudentButton.setBounds(90, 110, 118, 50);

        UpdateStudentButton.setText("Update Student");
        UpdateStudentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpdateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateStudentButton);
        UpdateStudentButton.setBounds(240, 110, 118, 50);

        DeleteStudentButton.setText("Delete Student");
        DeleteStudentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteStudentButton);
        DeleteStudentButton.setBounds(390, 110, 118, 50);

        SearchStudentButton.setText("Search Student");
        SearchStudentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SearchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchStudentButton);
        SearchStudentButton.setBounds(150, 190, 118, 50);

        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(20, 20, 60, 20);

        ShowListStudentButton.setText("Show Student List");
        ShowListStudentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ShowListStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowListStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShowListStudentButton);
        ShowListStudentButton.setBounds(320, 190, 118, 50);

        ExitButton.setForeground(new java.awt.Color(204, 0, 0));
        ExitButton.setText("Exit");
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(500, 260, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void UpdateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_UpdateStudentButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new DeleteStudentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void SearchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentButtonActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run(){
               new SearchStudentForm().setVisible(true);
           }
       });
       this.dispose();
    }//GEN-LAST:event_SearchStudentButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
        this.dispose();

    }//GEN-LAST:event_BackButtonActionPerformed

    private void ShowListStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowListStudentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new ShowListStudentForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ShowListStudentButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchStudentButton;
    private javax.swing.JButton ShowListStudentButton;
    private javax.swing.JButton UpdateStudentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
