package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class UpdateStudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateStudentForm.class.getName());

    Connection conn=null;
    PreparedStatement pst=null;
    Statement st=null;
    ResultSet rs=null;
    
    public UpdateStudentForm() {
        initComponents();
        setExtendedState(UpdateStudentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Department = new javax.swing.JComboBox<>();
        Year = new javax.swing.JSpinner();
        GPA = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        EnterStudentID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentInformation = new javax.swing.JTextArea();
        SearchStudentID = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, -8, 200, 50);

        jLabel2.setText("StudentID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 270, 70, 20);

        jLabel3.setText("Name: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 300, 60, 20);
        getContentPane().add(StudentID);
        StudentID.setBounds(120, 270, 120, 22);
        getContentPane().add(Name);
        Name.setBounds(120, 300, 120, 22);

        jLabel4.setText("Surname:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 330, 60, 20);
        getContentPane().add(Surname);
        Surname.setBounds(120, 330, 120, 22);

        jLabel5.setText("Gender:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 360, 50, 20);

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(Gender);
        Gender.setBounds(120, 360, 72, 22);

        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 270, 60, 20);

        Email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(410, 270, 160, 22);

        jLabel7.setText("Department:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 290, 80, 40);

        jLabel8.setText("Year:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 310, 60, 60);

        jLabel9.setText("GPA:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 360, 50, 30);

        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Computer Engineering", "Electrical Engineering", "Electronics Engineering", "Mechanical Engineering", "Civil Engineering", "Industrial Engineering", "Artificial Intelligence", "Data Science", "Information Systems", "Business Administration", "Economics", "International Relations", "Psychology", "Mathematics", "Physics", "Chemistry", "Biology", "Medicine", "Law", "Architecture" }));
        getContentPane().add(Department);
        Department.setBounds(410, 300, 160, 22);
        getContentPane().add(Year);
        Year.setBounds(410, 330, 70, 22);
        getContentPane().add(GPA);
        GPA.setBounds(410, 360, 64, 22);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(150, 420, 100, 40);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(350, 420, 100, 40);

        jLabel10.setText("Enter Student ID:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 30, 110, 60);
        getContentPane().add(EnterStudentID);
        EnterStudentID.setBounds(160, 50, 240, 22);

        StudentInformation.setColumns(20);
        StudentInformation.setRows(5);
        jScrollPane2.setViewportView(StudentInformation);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 110, 500, 140);

        SearchStudentID.setText("Search");
        SearchStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentIDActionPerformed(evt);
            }
        });
        getContentPane().add(SearchStudentID);
        SearchStudentID.setBounds(422, 50, 80, 23);

        jLabel11.setText("Student Information");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 90, 130, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-7, -4, 620, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        if (StudentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student ID cannot be empty!");
            return;
        }
        if (Name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty!");
            return;
        }
        if (Surname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Surname cannot be empty!");
            return;
        }
        if (Email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email cannot be empty!");
            return;
        }
        if (GPA.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "GPA cannot be empty!");
            return;
        }
    
        String sql2="update Group2_Students set name=?, surname=?, gender=?, email=?, department=?, year=?, gpa=? where studentId=?;";
        try{
            conn=OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql2);
            pst.setString(1, Name.getText());
            pst.setString(2, Surname.getText());
            pst.setString(3, Gender.getSelectedItem().toString());
            pst.setString(4, Email.getText());
            pst.setString(5, Department.getSelectedItem().toString());
            pst.setString(6, Year.getValue().toString());
            pst.setString(7, GPA.getText());
            pst.setString(8, StudentID.getText());
            
            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Student Information Updated");
            }
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SearchStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentIDActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "select * from Group2_Students where StudentID=?";
            conn=OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql);
            pst.setString(1, EnterStudentID.getText().trim());
            rs=pst.executeQuery();
            
            if (rs.next()) {
            
            String id = rs.getString("StudentID");
            String name = rs.getString("Name");
            String surname = rs.getString("Surname");
            String gender = rs.getString("Gender");
            String email = rs.getString("Email");
            String department = rs.getString("Department");
            String year = rs.getString("Year");
            String gpa = rs.getString("GPA");
            
            
            StudentID.setText(id);
            Name.setText(name);
            Surname.setText(surname);
            Gender.setSelectedItem(gender);
            Email.setText(email);
            Department.setSelectedItem(department);
            Year.setValue(Integer.parseInt(year));
            GPA.setText(gpa);
            
            String studentInfo ="Student ID   : " + id + "\n" +
                         "Full Name    : " + name + " " + surname + "\n" +
                         "Gender       : " + gender + "\n" +
                         "Email        : " + email + "\n" +
                         "Department   : " + department + "\n" +
                         "Year         : " + year + "\n" +
                         "GPA          : " + gpa;
            StudentInformation.setText(studentInfo);
            
            }else {
                JOptionPane.showMessageDialog(null, "Student Not Found!");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_SearchStudentIDActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateStudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField EnterStudentID;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField GPA;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Name;
    private javax.swing.JButton SearchStudentID;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextArea StudentInformation;
    private javax.swing.JTextField Surname;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JSpinner Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
