package studentManagementSystem;

import java.sql.*;
import javax.swing.JOptionPane;
public class UpdateEnrollmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateEnrollmentForm.class.getName());

    Connection conn=null;
    PreparedStatement pst=null;
    Statement st=null;
    ResultSet rs=null;
    
    public UpdateEnrollmentForm() {
        initComponents();
        setExtendedState(UpdateEnrollmentForm.MAXIMIZED_BOTH);
        conn=OnlineDB.connectOnlineDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CourseCode = new javax.swing.JTextField();
        Credits = new javax.swing.JTextField();
        StudentID = new javax.swing.JTextField();
        CourseName = new javax.swing.JTextField();
        UpdateEnrollmentButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        EnrollmentID = new javax.swing.JTextField();
        SearchEnrollmentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnrollmentInformation = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update Enrollment");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 230, 100);

        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 300, 70, 20);

        jLabel3.setText("Course Code:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 330, 80, 20);

        jLabel4.setText("Course Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 300, 80, 20);

        jLabel5.setText("Credits:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 330, 50, 20);
        getContentPane().add(CourseCode);
        CourseCode.setBounds(130, 330, 170, 22);
        getContentPane().add(Credits);
        Credits.setBounds(440, 330, 170, 22);
        getContentPane().add(StudentID);
        StudentID.setBounds(130, 300, 170, 22);
        getContentPane().add(CourseName);
        CourseName.setBounds(440, 300, 170, 22);

        UpdateEnrollmentButton.setText("Update");
        UpdateEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateEnrollmentButton);
        UpdateEnrollmentButton.setBounds(230, 400, 80, 30);

        ExitButton.setText("Back");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(360, 400, 80, 30);

        jLabel6.setText("Enter Enrollment ID:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 100, 130, 20);
        getContentPane().add(EnrollmentID);
        EnrollmentID.setBounds(220, 100, 200, 22);

        SearchEnrollmentButton.setText("Search");
        SearchEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEnrollmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchEnrollmentButton);
        SearchEnrollmentButton.setBounds(440, 100, 80, 23);

        EnrollmentInformation.setColumns(20);
        EnrollmentInformation.setRows(5);
        jScrollPane1.setViewportView(EnrollmentInformation);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 150, 340, 120);

        jLabel7.setText("Enrollment Information");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 130, 160, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentManagementSystem/pictureLast.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-3, -4, 690, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEnrollmentButtonActionPerformed
        // TODO add your handling code here:
        if (EnrollmentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please search and load an enrollment first!");
            return;
        }
        if (StudentID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student ID cannot be empty!");
            return;
        }
        if (CourseCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course Code cannot be empty!");
            return;
        }
        if (CourseName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course Name cannot be empty!");
            return;
        }
        if (Credits.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Credits cannot be empty!");
            return;
        }
        
        String sql="update Group2_Enrollments set StudentID=?, CourseCode=?, CourseName=?, Credits=? where EnrollmentID=?";
        try{
            conn = OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql);
            pst.setString(1, StudentID.getText());
            pst.setString(2, CourseCode.getText());
            pst.setString(3, CourseName.getText());
            pst.setString(4, Credits.getText());
            pst.setString(5, EnrollmentID.getText());
            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Enrollment Updated");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
            
        }
    }//GEN-LAST:event_UpdateEnrollmentButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentManagement().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SearchEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEnrollmentButtonActionPerformed
        // TODO add your handling code here:
       
        String sql="select * from Group2_Enrollments where EnrollmentID=?";
        try{
            conn = OnlineDB.connectOnlineDB();
            pst=conn.prepareStatement(sql);
            pst.setString(1, EnrollmentID.getText());
            rs=pst.executeQuery();
            
            if (rs.next()) {
            
                String studentId = rs.getString("StudentID");
                String courseCode = rs.getString("CourseCode");
                String courseName = rs.getString("CourseName");
                String credits = rs.getString("Credits");
                
                StudentID.setText(studentId);
                CourseCode.setText(courseCode);
                CourseName.setText(courseName);
                Credits.setText(credits);
                
                String info = "Enrollment ID: " + EnrollmentID.getText() + "\n" +
                  "Student ID: " + StudentID.getText() + "\n" +
                  "Course: " + CourseName.getText() + " (" + CourseCode.getText() + ")\n" +
                  "Credits: " + Credits.getText();
                
                EnrollmentInformation.setText(info);
                
            } else {
                JOptionPane.showMessageDialog(null, "Enrollment Not Found!");
            }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_SearchEnrollmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateEnrollmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseCode;
    private javax.swing.JTextField CourseName;
    private javax.swing.JTextField Credits;
    private javax.swing.JTextField EnrollmentID;
    private javax.swing.JTextArea EnrollmentInformation;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SearchEnrollmentButton;
    private javax.swing.JTextField StudentID;
    private javax.swing.JButton UpdateEnrollmentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
